language: php

php:
  - 5.6
  - 7.0

before_script:
  - composer install --dev --prefer-source --no-interaction --prefer-source
  - cp .env.tavis .env
  - php artisan key:generate

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs app --standard=PSR2
